### ISSUE TITLE
change the namespace listening to

### ISSUE THREAD

**Issue by Hackmeat** [observatorium/thanos-receive-controller#124]
Hi,
i have the issue that my Thanos is running on a different namespace, not on the default one which is configured in the main.go..
Is there flag with which i can change it from "default" to "whatever"

**Comment by mikeacameron** [comment]
The `namespace` configuration is what you're looking for. You can see an example here: https://github.com/observatorium/thanos-receive-controller/blob/c57219e684d688af580e7cb8d7d8e96a8f939c6b/examples/manifests/deployment.yaml#L31

This will configure the controller to listen in the name namespace it's deployed to.

**Comment by Hackmeat** [comment]
thx, maybe will help someone, we switched away from thanos due to high perfomance cost compared to mimir

**Comment by Hackmeat** [comment]
see above
