### ISSUE TITLE
Support Multi-AZ in HashRing Config

### ISSUE THREAD

**Issue by christopherzli** [observatorium/thanos-receive-controller#127]
As thanos support az aware hashring config starting from v0.32: https://thanos.io/tip/components/receive.md/#az-aware-ketama-hashring-experimental, we should support multi az in the controller to update config as well.

**Comment by christopherzli** [comment]
pull request here: https://github.com/observatorium/thanos-receive-controller/pull/129

**Comment by algo7** [comment]
This would appreciated. At the moment it seems to not support Ketama AZ-aware hashring as mentioned in Thanos official documentation here: https://thanos.io/tip/components/receive.md/#az-aware-ketama-hashring-experimental

Using the config provided in Thanos doc results in the controller throwing error
```
level=warn caller=main.go:547 ts=2024-05-01T04:56:39.561782951Z msg="failed to decode configuration" err="json: cannot unmarshal object into Go struct field HashringConfig.endpoints of type string"
```

**Comment by christopherzli** [comment]
thanks @algo7 , hope this PR could be reviewed soon 😄
