### ISSUE TITLE
Docker - Support Arm Architecture

### ISSUE THREAD

**Issue by ryanmcafee** [observatorium/thanos-receive-controller#94]
We use ARM based Graviton instances in AWS and need ARM support for running thanos-receive-controller.
It would be nice if the project supported building multiple architectures in the Github Actions publish pipeline to support use cases like ours.

**Comment by douglascamata** [comment]
Since 78423a74a86498887dff7b0ba4471f2db91bf787 we have now arm64 images. #95 was superseded by #98. 

Thanks a lot for the work on #95 and I'm sorry we didn't merge it, @ryanmcafee. #98 uses the same base system for multi-arch images than many other projects under the org, so it was preferred.
